version: '3'

services:

  sense_module:
    build:
      context: ./sense
      dockerfile: Dockerfile
    container_name: sense_module
    hostname: sense_module
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - TZ=Europe/Rome

  action_module:
    build:
      context: ./action
      dockerfile: Dockerfile
    container_name: action_module
    hostname: action_module
    ports:
      - "8090:8090"
    expose:
      - 8090
    environment:
      - TZ=Europe/Rome

  perc_module:
    build:
      context: ./perception
      dockerfile: Dockerfile
    container_name: perc_module
    hostname: perc_module
    ports:
      - "8100:8100"
    expose:
      - 8100
    environment:
      - TZ=Europe/Rome
    depends_on:
      - sense_module

  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    container_name: controller
    hostname: controller
    ports:
      - "8110:8110"
    expose:
      - 8110
    depends_on:
      - sense_module
      - action_module
      - perc_module

